\set ON_ERROR_STOP on
DROP ROLE pgreact_mdm_worker;
CREATE ROLE pgreact_mdm_worker
    NOLOGIN NOSUPERUSER NOBYPASSRLS NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT pgreact_mdm_worker TO mdm_m2_runner WITH SET TRUE, INHERIT FALSE;
